services:
  app:
    build: .
    container_name: inspirtag-app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/laravel.conf
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    depends_on:
      - redis
    networks:
      - inspirtag-network
    healthcheck:
      test: ["CMD", "supervisorctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: inspirtag-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - inspirtag-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: inspirtag-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - inspirtag-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:

networks:
  inspirtag-network:
    driver: bridge

